### ISSUE TITLE
Create a function to webscraper

### ISSUE THREAD

**Issue by Machado21** [Machado21/api-logistica#3]
Webscraper to get NFe informations (Número NFe, data da Emissão, Transportadora, valor, **produtos(Código, Descrição, Quantidade)) from site ( https://www.nfe.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=resumo&tipoConteudo=7PhJ+gAVw2g= ) 

Save on MongoDB

**Comment by brunorcx** [comment]
This can't be done with the current tools. We need to use the official API by the gov in order to avoid legal action

**Comment by brunorcx** [comment]
Not possible at the momement
